version: '3'
services:

    # The Application
    app:
        build:
            context: .
        #   dockerfile: app.dockerfile
        working_dir: /var/www/
        container_name: php
        hostname: php
        volumes:
            - ./src:/var/www/
        ports:
            - 9000:9000

    # The Web Server
    web:
        image: nginx:1.18
        working_dir: /var/www/
        container_name: nginx
        hostname: nginx
        volumes: 
            - ./src:/var/www/
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80